# this is redis config file
[list]
    [list.default]
        proxy_list = ["10.194.59.97:6379"]
        max_active = 100
        max_idle = 100
        down_grade = false
        password = "qyydhm"
